require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '13.4'
prepare_react_native_project!

target 'CropCareAI' do
  config = use_native_modules!
  pod 'TensorFlowLite', '1.12.0'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  target 'CropCareAITests' do
    inherit! :complete
    # Pods for testing
  end

  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end